# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流任务
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Skopeo
      run: |
        sudo apt-get update -y
        sudo apt-get install -y skopeo
    # 添加 JDCloud 登录步骤
    - name: Login to JDCloud Docker Registry
      run: |
        echo "${{ secrets.JDCLOUD_PASSWORD }}" | docker login -u "${{ secrets.JDCLOUD_USERNAME }}" --password-stdin bot-cn-north-1.jcr.service.jdcloud.com
    - name: Sync Image to JDCloud
      run: |
        skopeo copy docker://gcr.io/kaniko-project/executor:v1.13.0 docker://bot-cn-north-1.jcr.service.jdcloud.com/your-namespace/kaniko-executor:v1.13.0
